package assets.constants

import models.team.Team
import play.api.libs.json.Json

object TeamsJsonConstants {

  val arsenalJson = Json.obj(
    "code" -> 3,
    "draw" -> 0,
    "form" -> "",
    "id" -> 1,
    "loss" -> 0,
    "name" -> "Arsenal",
    "played" -> 0,
    "points" -> 0,
    "position" -> 0,
    "short_name" -> "ARS",
    "strength" -> 4,
    "team_division" -> 1,
    "unavailable" -> false,
    "win" -> 0,
    "strength_overall_home" -> 1190,
    "strength_overall_away" -> 1270,
    "strength_attack_home" -> 1190,
    "strength_attack_away" -> 1200,
    "strength_defence_home" -> 1160,
    "strength_defence_away" -> 1270,
    "pulse_id" -> 1
  )

  val villaJson = Json.obj(
    "code" -> 7,
    "draw" -> 0,
    "form" -> "",
    "id" -> 2,
    "loss" -> 0,
    "name" -> "Aston Villa",
    "played" -> 0,
    "points" -> 0,
    "position" -> 0,
    "short_name" -> "AVL",
    "strength" -> 2,
    "team_division" -> 1,
    "unavailable" -> false,
    "win" -> 0,
    "strength_overall_home" -> 1050,
    "strength_overall_away" -> 1080,
    "strength_attack_home" -> 1010,
    "strength_attack_away" -> 1080,
    "strength_defence_home" -> 1000,
    "strength_defence_away" -> 1110,
    "pulse_id" -> 2
  )

  val brightonJson = Json.obj(
    "code" -> 36,
    "draw" -> 0,
    "form" -> "",
    "id" -> 3,
    "loss" -> 0,
    "name" -> "Brighton",
    "played" -> 0,
    "points" -> 0,
    "position" -> 0,
    "short_name" -> "BHA",
    "strength" -> 2,
    "team_division" -> 1,
    "unavailable" -> false,
    "win" -> 0,
    "strength_overall_home" -> 1070,
    "strength_overall_away" -> 1070,
    "strength_attack_home" -> 1100,
    "strength_attack_away" -> 1130,
    "strength_defence_home" -> 1060,
    "strength_defence_away" -> 1060,
    "pulse_id" -> 131
  )
  val burnleyJson = Json.obj(
    "code" -> 90,
    "draw" -> 0,
    "form" -> "",
    "id" -> 4,
    "loss" -> 0,
    "name" -> "Burnley",
    "played" -> 0,
    "points" -> 0,
    "position" -> 0,
    "short_name" -> "BUR",
    "strength" -> 3,
    "team_division" -> 1,
    "unavailable" -> false,
    "win" -> 0,
    "strength_overall_home" -> 1140,
    "strength_overall_away" -> 1150,
    "strength_attack_home" -> 1130,
    "strength_attack_away" -> 1240,
    "strength_defence_home" -> 1050,
    "strength_defence_away" -> 1170,
    "pulse_id" -> 43
  )
  val chelseaJson = Json.obj(
    "code" -> 8,
    "draw" -> 0,
    "form" -> "",
    "id" -> 5,
    "loss" -> 0,
    "name" -> "Chelsea",
    "played" -> 0,
    "points" -> 0,
    "position" -> 0,
    "short_name" -> "CHE",
    "strength" -> 4,
    "team_division" -> 1,
    "unavailable" -> false,
    "win" -> 0,
    "strength_overall_home" -> 1200,
    "strength_overall_away" -> 1260,
    "strength_attack_home" -> 1140,
    "strength_attack_away" -> 1270,
    "strength_defence_home" -> 1240,
    "strength_defence_away" -> 1250,
    "pulse_id" -> 4
  )
  val palaceJson = Json.obj(
    "code" -> 31,
    "draw" -> 0,
    "form" -> "",
    "id" -> 6,
    "loss" -> 0,
    "name" -> "Crystal Palace",
    "played" -> 0,
    "points" -> 0,
    "position" -> 0,
    "short_name" -> "CRY",
    "strength" -> 3,
    "team_division" -> 1,
    "unavailable" -> false,
    "win" -> 0,
    "strength_overall_home" -> 1080,
    "strength_overall_away" -> 1070,
    "strength_attack_home" -> 1080,
    "strength_attack_away" -> 1190,
    "strength_defence_home" -> 1010,
    "strength_defence_away" -> 1040,
    "pulse_id" -> 6
  )
  val evertonJson = Json.obj(
    "code" -> 11,
    "draw" -> 0,
    "form" -> "",
    "id" -> 7,
    "loss" -> 0,
    "name" -> "Everton",
    "played" -> 0,
    "points" -> 0,
    "position" -> 0,
    "short_name" -> "EVE",
    "strength" -> 3,
    "team_division" -> 1,
    "unavailable" -> false,
    "win" -> 0,
    "strength_overall_home" -> 1100,
    "strength_overall_away" -> 1180,
    "strength_attack_home" -> 1090,
    "strength_attack_away" -> 1190,
    "strength_defence_home" -> 1150,
    "strength_defence_away" -> 1180,
    "pulse_id" -> 7
  )
  val fulhamJson = Json.obj(
    "code" -> 54,
    "draw" -> 0,
    "form" -> "",
    "id" -> 8,
    "loss" -> 0,
    "name" -> "Fulham",
    "played" -> 0,
    "points" -> 0,
    "position" -> 0,
    "short_name" -> "FUL",
    "strength" -> 2,
    "team_division" -> 1,
    "unavailable" -> false,
    "win" -> 0,
    "strength_overall_home" -> 1000,
    "strength_overall_away" -> 1030,
    "strength_attack_home" -> 1010,
    "strength_attack_away" -> 1030,
    "strength_defence_home" -> 1000,
    "strength_defence_away" -> 1050,
    "pulse_id" -> 34
  )
  val leicesterJson = Json.obj(
    "code" -> 13,
    "draw" -> 0,
    "form" -> "",
    "id" -> 9,
    "loss" -> 0,
    "name" -> "Leicester",
    "played" -> 0,
    "points" -> 0,
    "position" -> 0,
    "short_name" -> "LEI",
    "strength" -> 4,
    "team_division" -> 1,
    "unavailable" -> false,
    "win" -> 0,
    "strength_overall_home" -> 1180,
    "strength_overall_away" -> 1230,
    "strength_attack_home" -> 1180,
    "strength_attack_away" -> 1260,
    "strength_defence_home" -> 1220,
    "strength_defence_away" -> 1250,
    "pulse_id" -> 26
  )
  val leedsJson = Json.obj(
    "code" -> 2,
    "draw" -> 0,
    "form" -> "",
    "id" -> 10,
    "loss" -> 0,
    "name" -> "Leeds",
    "played" -> 0,
    "points" -> 0,
    "position" -> 0,
    "short_name" -> "LEE",
    "strength" -> 2,
    "team_division" -> 1,
    "unavailable" -> false,
    "win" -> 0,
    "strength_overall_home" -> 1030,
    "strength_overall_away" -> 1040,
    "strength_attack_home" -> 1040,
    "strength_attack_away" -> 1070,
    "strength_defence_home" -> 990,
    "strength_defence_away" -> 990,
    "pulse_id" -> 9
  )
  val liverpoolJson = Json.obj(
    "code" -> 14,
    "draw" -> 0,
    "form" -> "",
    "id" -> 11,
    "loss" -> 0,
    "name" -> "Liverpool",
    "played" -> 0,
    "points" -> 0,
    "position" -> 0,
    "short_name" -> "LIV",
    "strength" -> 5,
    "team_division" -> 1,
    "unavailable" -> false,
    "win" -> 0,
    "strength_overall_home" -> 1320,
    "strength_overall_away" -> 1350,
    "strength_attack_home" -> 1280,
    "strength_attack_away" -> 1320,
    "strength_defence_home" -> 1300,
    "strength_defence_away" -> 1340,
    "pulse_id" -> 10
  )
  val manCityJson = Json.obj(
    "code" -> 43,
    "draw" -> 0,
    "form" -> "",
    "id" -> 12,
    "loss" -> 0,
    "name" -> "Man City",
    "played" -> 0,
    "points" -> 0,
    "position" -> 0,
    "short_name" -> "MCI",
    "strength" -> 5,
    "team_division" -> 1,
    "unavailable" -> false,
    "win" -> 0,
    "strength_overall_home" -> 1310,
    "strength_overall_away" -> 1350,
    "strength_attack_home" -> 1250,
    "strength_attack_away" -> 1340,
    "strength_defence_home" -> 1340,
    "strength_defence_away" -> 1350,
    "pulse_id" -> 11
  )
  val manUtdJson = Json.obj(
    "code" -> 1,
    "draw" -> 0,
    "form" -> "",
    "id" -> 13,
    "loss" -> 0,
    "name" -> "Man Utd",
    "played" -> 0,
    "points" -> 0,
    "position" -> 0,
    "short_name" -> "MUN",
    "strength" -> 4,
    "team_division" -> 1,
    "unavailable" -> false,
    "win" -> 0,
    "strength_overall_home" -> 1250,
    "strength_overall_away" -> 1250,
    "strength_attack_home" -> 1250,
    "strength_attack_away" -> 1260,
    "strength_defence_home" -> 1200,
    "strength_defence_away" -> 1290,
    "pulse_id" -> 12
  )
  val newcastleJson = Json.obj(
    "code" -> 4,
    "draw" -> 0,
    "form" -> "",
    "id" -> 14,
    "loss" -> 0,
    "name" -> "Newcastle",
    "played" -> 0,
    "points" -> 0,
    "position" -> 0,
    "short_name" -> "NEW",
    "strength" -> 3,
    "team_division" -> 1,
    "unavailable" -> false,
    "win" -> 0,
    "strength_overall_home" -> 1090,
    "strength_overall_away" -> 1120,
    "strength_attack_home" -> 1040,
    "strength_attack_away" -> 1170,
    "strength_defence_home" -> 1020,
    "strength_defence_away" -> 1070,
    "pulse_id" -> 23
  )
  val sheffUJson = Json.obj(
    "code" -> 49,
    "draw" -> 0,
    "form" -> "",
    "id" -> 15,
    "loss" -> 0,
    "name" -> "Sheffield Utd",
    "played" -> 0,
    "points" -> 0,
    "position" -> 0,
    "short_name" -> "SHU",
    "strength" -> 3,
    "team_division" -> 1,
    "unavailable" -> false,
    "win" -> 0,
    "strength_overall_home" -> 1170,
    "strength_overall_away" -> 1220,
    "strength_attack_home" -> 1160,
    "strength_attack_away" -> 1280,
    "strength_defence_home" -> 1010,
    "strength_defence_away" -> 1150,
    "pulse_id" -> 18
  )
  val sotonJson = Json.obj(
    "code" -> 20,
    "draw" -> 0,
    "form" -> "",
    "id" -> 16,
    "loss" -> 0,
    "name" -> "Southampton",
    "played" -> 0,
    "points" -> 0,
    "position" -> 0,
    "short_name" -> "SOU",
    "strength" -> 3,
    "team_division" -> 1,
    "unavailable" -> false,
    "win" -> 0,
    "strength_overall_home" -> 1150,
    "strength_overall_away" -> 1060,
    "strength_attack_home" -> 1140,
    "strength_attack_away" -> 1060,
    "strength_defence_home" -> 1190,
    "strength_defence_away" -> 1090,
    "pulse_id" -> 20
  )
  val spursJson = Json.obj(
    "code" -> 6,
    "draw" -> 0,
    "form" -> "",
    "id" -> 17,
    "loss" -> 0,
    "name" -> "Spurs",
    "played" -> 0,
    "points" -> 0,
    "position" -> 0,
    "short_name" -> "TOT",
    "strength" -> 4,
    "team_division" -> 1,
    "unavailable" -> false,
    "win" -> 0,
    "strength_overall_home" -> 1200,
    "strength_overall_away" -> 1260,
    "strength_attack_home" -> 1100,
    "strength_attack_away" -> 1240,
    "strength_defence_home" -> 1200,
    "strength_defence_away" -> 1260,
    "pulse_id" -> 21
  )
  val wbaJson = Json.obj(
    "code" -> 35,
    "draw" -> 0,
    "form" -> "",
    "id" -> 18,
    "loss" -> 0,
    "name" -> "West Brom",
    "played" -> 0,
    "points" -> 0,
    "position" -> 0,
    "short_name" -> "WBA",
    "strength" -> 2,
    "team_division" -> 1,
    "unavailable" -> false,
    "win" -> 0,
    "strength_overall_home" -> 1020,
    "strength_overall_away" -> 1030,
    "strength_attack_home" -> 1030,
    "strength_attack_away" -> 1030,
    "strength_defence_home" -> 1020,
    "strength_defence_away" -> 1150,
    "pulse_id" -> 36
  )
  val whuJson = Json.obj(
    "code" -> 21,
    "draw" -> 0,
    "form" -> "",
    "id" -> 19,
    "loss" -> 0,
    "name" -> "West Ham",
    "played" -> 0,
    "points" -> 0,
    "position" -> 0,
    "short_name" -> "WHU",
    "strength" -> 3,
    "team_division" -> 1,
    "unavailable" -> false,
    "win" -> 0,
    "strength_overall_home" -> 1070,
    "strength_overall_away" -> 1100,
    "strength_attack_home" -> 1090,
    "strength_attack_away" -> 1090,
    "strength_defence_home" -> 1040,
    "strength_defence_away" -> 1210,
    "pulse_id" -> 25
  )
  val wolvesJson = Json.obj(
    "code" -> 39,
    "draw" -> 0,
    "form" -> "",
    "id" -> 20,
    "loss" -> 0,
    "name" -> "Wolves",
    "played" -> 0,
    "points" -> 0,
    "position" -> 0,
    "short_name" -> "WOL",
    "strength" -> 3,
    "team_division" -> 1,
    "unavailable" -> false,
    "win" -> 0,
    "strength_overall_home" -> 1200,
    "strength_overall_away" -> 1190,
    "strength_attack_home" -> 1230,
    "strength_attack_away" -> 1250,
    "strength_defence_home" -> 1170,
    "strength_defence_away" -> 1200,
    "pulse_id" -> 38
  )


  val teams: Seq[Team] = Seq(
    arsenalJson.as[Team],
    villaJson.as[Team],
    brightonJson.as[Team],
    burnleyJson.as[Team],
    chelseaJson.as[Team],
    palaceJson.as[Team],
    evertonJson.as[Team],
    fulhamJson.as[Team],
    leicesterJson.as[Team],
    leedsJson.as[Team],
    liverpoolJson.as[Team],
    manCityJson.as[Team],
    manUtdJson.as[Team],
    newcastleJson.as[Team],
    sheffUJson.as[Team],
    sotonJson.as[Team],
    spursJson.as[Team],
    wbaJson.as[Team],
    wolvesJson.as[Team],

  )
}
